### ISSUE TITLE
dojo.io.script error

### ISSUE THREAD

**Issue by Bluedhh** [Esri/wind-js#19]
when I put the code in myeclipse with tomcat, it did not work and show error : dojo.io.script error .I am a new programma and it is a little problem ,but please tell me how to build the sever in this program.

**Comment by jgravois** [comment]
do you also see a web request for RasterLayer.js that 404s when the application loads?
if so, how exactly are you attempting to load the application in a browser?

when i copied the files down into the root of my own web server and accessed them via http://localhost/index.html, everything displayed correctly for me.

**Comment by akiohansen** [comment]
Hey everyone, I've the same problem like Bluedhh... I also get the following dojo.io.script error: "dojo.io.script error Error: Token Required.", when I'm trying to run the escri/wind-js project, which is really cool! Thanks!

Does anybody have an idea how to fix this issue? Thanks a lot!

**Comment by jgravois** [comment]
@akiohansen 
* how *exactly* are you attempting to host the web application files?  
* how *exactly* are you attempting to access the application in the browser?
* do you see anything unexpected in the [network](https://developer.chrome.com/devtools#improving-network-performance) traffic?

**Comment by akiohansen** [comment]
@jgravois 

- I've copied all your github files to my Apache webserver, which has also node-js installed.
- I try to access the application by calling the index.html file in my webbrowser (Google Chrome), here is my installation of this app: http://37.120.170.199/mds/wind-js/index.html
- Within the network traffic there seem to be nothing unexpected, except of this dojo.io.script error. There is one more warning, perhaps this helps you:
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/."

Do you have any idea how to get this very cool application running on my own server? Thanks a lot for all your work and your support!!! ;-)

**Comment by jgravois** [comment]
thanks for the additional info.  

you're seeing this because the code in the [`master`](https://github.com/Esri/wind-js/blob/master/index.html#L57) branch of the repository points at a custom dark gray basemap which is no longer publicly accessible.  if you use the code in our [`gh-pages`](https://github.com/Esri/wind-js/blob/gh-pages/index.html) branch (which powers our live sample), everything works as expected.

i'll fix this problem and bump the ArcGIS API for JavaScript version in use here as soon as i get a chance.

in general, i recommend that we blow away the master branch entirely as i believe its doing more harm than good to maintain and syncronize both.

**Comment by akiohansen** [comment]
Great! Thank you very much for your very helpful support and the project in general!!!
Now, everythin works as it should do. I've now used the gh-pages branch as suggested. ;-)
Thanks a lot and all the best!

**Comment by jgravois** [comment]
you're very welcome.
