### ISSUE TITLE
use on an existing leaflet map

### ISSUE THREAD

**Issue by sidharthskumar** [Esri/wind-js#36]
how can i add this to my existing leaflet map

**Comment by jgravois** [comment]
> how can i add this to my existing leaflet map

what have you tried?

this code sample directly manipulates an HTML [canvas](https://caniuse.com/#feat=canvas) so _theoretically_ it could be ported.

https://github.com/Esri/wind-js/blob/5fee5c73a26c21f801dcd414c64e31fb7cc1a1f0/index.html#L88-L99

**Comment by sidharthskumar** [comment]
Please help me import it..please here is my html file
[keralafish(2).txt](https://github.com/Esri/wind-js/files/3165397/keralafish.2.txt)

**Comment by jgravois** [comment]
an abstract question like, 'tell me everything that would have to be different to use this code with an entirely different mapping API' is a little too ambitious for a GitHub issue.

in order to increase the chances of anyone else online being able to help you you'll need to try and frame a more specific question, test a hypothesis on your own and articulate what you learned.

**Comment by sidharthskumar** [comment]
please
